server.port: 8084

solon.app:
  name: 'AuroraTimerServer'
  group: 'aurora'

solon.cache1:
  driverType: "caffeine"

solon.threads.virtual.enabled: true
# 设定 http gzip配置
server.http.gzip.enable: true  #是否启用（默认 fasle）
server.http.gzip.minSize: 4096 #最小多少大小才启用（默认 4k）
server.http.gzip.mimeTypes: 'text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml'

mybatis-flex:
  #  mybatis-flex 数据源配置
  datasource:
    db1:
      type: "com.zaxxer.hikari.HikariDataSource"
      jdbcUrl: "jdbc:postgresql://localhost:5432/timer_pg"
      driverClassName: "org.postgresql.Driver"
      username: "postgres"
      password: "${DB_PSW}"
  #  mybatis-flex 其它配置
  type-aliases-package: #支持包名 或 类名（大写开头 或 *）//支持 ** 或 * 占位符
    - "com.aurora.day.auroratimerserver.model"
  mapper-locations: #支持包名 或 类名（大写开头 或 *）或 xml（.xml结尾）//支持 ** 或 * 占位符
    - "com.aurora.day.auroratimerserver.mapper"
  configuration: #扩展配置（要与 FlexConfiguration 类的属性一一对应）
    cacheEnabled: false
    mapUnderscoreToCamelCase: true
  global-config: #全局配置（要与 FlexGlobalConfig 类的属性一一对应）//只是示例，别照抄
    printBanner: false

solon.logging.appender:
  console:
    level: TRACE
    enable: true #是否启用
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-56(%cyan(%-40.40logger{39}%L)) : %msg%n" #Spring Boot风格格式
  file:
    name: "logs/${solon.app.name}"
    level: INFO
    enable: true #是否启用
    extension: ".log.gz"
    maxFileSize: "50 MB"
    maxHistory: "7"
    pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-56(%-40.40logger{39}%L) : %msg%n" #Spring Boot风格格式

##静态文件配置
solon.staticfiles.mappings:
  ## 头像目录映射
  - path: "static/avatar/" #路径，可以是目录或单文件
    repository: "${timer.filePath}/avatar/" #1.添加本地绝对目录（仓库只能是目录）

##Timer 项目配置
timer:
  ##文件路径，用于存放头像等文件。
  filePath: D:\project
  ##网络路径，用于将本地资源转换为url路径。
  hostPath: http://localhost:8084/static/